name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - b2cpolicymanager-cli/b2cpolicymanager-cli.csproj
          - B2CPolicyManagerUI/B2CPolicyManagerUI.csproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.project }}

    - name: Build
      run: dotnet build ${{ matrix.project }} --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ matrix.project }} --configuration Release --no-restore --output ./output/${{ matrix.project }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}
        path: ./output/${{ matrix.project }}
